sonar.projectKey=Nikita-hub000_go-project-244
sonar.organization=nikita-hub000
sonar.projectName=go-project-244
sonar.sources=.
sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.exclusions=**/testdata/**,**/.gocache/**
sonar.go.coverage.reportPaths=coverage.out
